/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => GDriveVaultSync
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  clientId: "",
  clientSecret: "",
  refreshToken: "",
  driveFolderName: "ObsidianVaultSync",
  autoSyncInterval: 30,
  autoSyncOnStart: true
};
var GDriveVaultSync = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.accessToken = "";
    this.tokenExpiry = 0;
    this.driveFolderId = "";
    this.isSyncing = false;
    this.syncIntervalId = null;
    this.lastSynced = {};
    this.statusBarEl = null;
  }
  // ── Lifecycle ────────────────────────────────
  async onload() {
    var _a, _b;
    try {
      await this.loadSettings();
      this.lastSynced = (_b = (_a = await this.loadData()) == null ? void 0 : _a.lastSynced) != null ? _b : {};
      this.statusBarEl = this.addStatusBarItem();
      this.setStatus("idle");
      this.addSettingTab(new GDriveSyncSettingTab(this.app, this));
      this.addCommand({ id: "gdrive-full-sync", name: "Two-Way Sync Now", callback: () => this.fullTwoWaySync() });
      this.addCommand({ id: "gdrive-download-all", name: "Download All from Drive", callback: () => this.downloadAllFromDrive() });
      this.registerEvent(this.app.vault.on("modify", (file) => {
        if (file instanceof import_obsidian.TFile && this.hasCredentials())
          this.onFileModified(file);
      }));
      this.registerEvent(this.app.vault.on("create", (file) => {
        if (file instanceof import_obsidian.TFile && this.hasCredentials())
          this.onFileCreated(file);
      }));
      this.registerEvent(this.app.vault.on("delete", (file) => {
        if (file instanceof import_obsidian.TFile && this.hasCredentials())
          this.onFileDeleted(file);
      }));
      this.registerEvent(this.app.vault.on("rename", (file, oldPath) => {
        if (file instanceof import_obsidian.TFile && this.hasCredentials())
          this.onFileRenamed(file, oldPath);
      }));
      window.setTimeout(() => {
        this.silentUpdateCheck();
      }, 1e4);
      if (this.settings.autoSyncOnStart && this.hasCredentials()) {
        window.setTimeout(() => {
          this.startAutoSync();
        }, 5e3);
      }
    } catch (e) {
      console.error("[GDrive Sync] onload error:", this.errMsg(e));
    }
  }
  async onunload() {
    try {
      this.stopAutoSync();
      await this.persistLastSynced();
    } catch (e) {
      console.error("[GDrive Sync] onunload error:", this.errMsg(e));
    }
  }
  // ── Settings ─────────────────────────────────
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(Object.assign({}, this.settings, { lastSynced: this.lastSynced }));
  }
  async persistLastSynced() {
    var _a;
    const data = (_a = await this.loadData()) != null ? _a : {};
    await this.saveData(Object.assign({}, data, { lastSynced: this.lastSynced }));
  }
  hasCredentials() {
    var _a, _b, _c;
    return !!(((_a = this.settings) == null ? void 0 : _a.clientId) && ((_b = this.settings) == null ? void 0 : _b.clientSecret) && ((_c = this.settings) == null ? void 0 : _c.refreshToken));
  }
  // ── Helpers ────────────────────────────────
  errMsg(e) {
    if (!e)
      return "Unknown error (empty)";
    if (typeof e === "string")
      return e;
    if (e instanceof Error)
      return e.message || e.toString();
    try {
      const s = JSON.stringify(e);
      if (s && s !== "{}")
        return s;
    } catch (_) {
    }
    return String(e) || "Unknown error";
  }
  setStatus(state, extra) {
    var _a;
    try {
      if (!this.statusBarEl)
        return;
      const msgs = { idle: "\u23F8 GDrive Sync idle", syncing: "\u{1F504} Syncing...", error: "\u274C Sync failed" };
      this.statusBarEl.setText((_a = extra != null ? extra : msgs[state]) != null ? _a : "\u23F8 GDrive Sync");
    } catch (_) {
    }
  }
  arrayBufferToBase64(buffer) {
    const bytes = new Uint8Array(buffer);
    let binary = "";
    for (let i = 0; i < bytes.byteLength; i++)
      binary += String.fromCharCode(bytes[i]);
    return btoa(binary);
  }
  async runInBatches(items, batchSize, fn) {
    for (let i = 0; i < items.length; i += batchSize) {
      await Promise.all(items.slice(i, i + batchSize).map(fn));
    }
  }
  // ── Token ───────────────────────────────────
  async getAccessToken() {
    const now = Date.now();
    if (this.accessToken && now < this.tokenExpiry - 6e4)
      return this.accessToken;
    try {
      const resp = await (0, import_obsidian.requestUrl)({
        url: "https://oauth2.googleapis.com/token",
        method: "POST",
        headers: { "Content-Type": "application/x-www-form-urlencoded" },
        body: new URLSearchParams({
          client_id: this.settings.clientId,
          client_secret: this.settings.clientSecret,
          refresh_token: this.settings.refreshToken,
          grant_type: "refresh_token"
        }).toString()
      });
      if (resp.status >= 400)
        throw new Error(`Token refresh failed (${resp.status}): ${resp.text || JSON.stringify(resp.json)}`);
      this.accessToken = resp.json.access_token;
      this.tokenExpiry = now + resp.json.expires_in * 1e3;
      return this.accessToken;
    } catch (e) {
      const msg = this.errMsg(e);
      new import_obsidian.Notice(`[GDrive Sync] Token error: ${msg}`, 1e4);
      throw new Error(msg);
    }
  }
  // ── Drive folder ───────────────────────────
  async getFolderId() {
    if (this.driveFolderId)
      return this.driveFolderId;
    const token = await this.getAccessToken();
    const folderName = this.settings.driveFolderName;
    const searchResp = await (0, import_obsidian.requestUrl)({
      url: `https://www.googleapis.com/drive/v3/files?q=${encodeURIComponent(`name='${folderName}' and mimeType='application/vnd.google-apps.folder' and trashed=false`)}&fields=files(id,name)`,
      method: "GET",
      headers: { Authorization: `Bearer ${token}` }
    });
    if (searchResp.status >= 400)
      throw new Error(`Drive folder search failed (${searchResp.status}): ${searchResp.text}`);
    const files = searchResp.json.files;
    if (files && files.length > 0) {
      this.driveFolderId = files[0].id;
      return this.driveFolderId;
    }
    const createResp = await (0, import_obsidian.requestUrl)({
      url: "https://www.googleapis.com/drive/v3/files",
      method: "POST",
      headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" },
      body: JSON.stringify({ name: folderName, mimeType: "application/vnd.google-apps.folder" })
    });
    if (createResp.status >= 400)
      throw new Error(`Drive folder create failed (${createResp.status}): ${createResp.text}`);
    this.driveFolderId = createResp.json.id;
    return this.driveFolderId;
  }
  // ── Path encoding ──────────────────────────
  encodePath(p) {
    return p.split("/").join("___");
  }
  decodePath(p) {
    return p.split("___").join("/");
  }
  // ── List Drive files ───────────────────────
  async listDriveFiles() {
    const token = await this.getAccessToken();
    const folderId = await this.getFolderId();
    const map = {};
    let pageToken = "";
    do {
      const qParams = new URLSearchParams({
        q: `'${folderId}' in parents and trashed=false`,
        fields: "nextPageToken,files(id,name,modifiedTime)",
        pageSize: "1000"
      });
      if (pageToken)
        qParams.set("pageToken", pageToken);
      const resp = await (0, import_obsidian.requestUrl)({
        url: `https://www.googleapis.com/drive/v3/files?${qParams.toString()}`,
        method: "GET",
        headers: { Authorization: `Bearer ${token}` }
      });
      if (resp.status >= 400)
        throw new Error(`Drive list failed (${resp.status}): ${resp.text}`);
      for (const f of resp.json.files) {
        map[this.decodePath(f.name)] = { id: f.id, modifiedTime: f.modifiedTime };
      }
      pageToken = resp.json.nextPageToken || "";
    } while (pageToken);
    return map;
  }
  // ── Download file ──────────────────────────
  async downloadFile(fileId, vaultPath) {
    const token = await this.getAccessToken();
    const resp = await (0, import_obsidian.requestUrl)({
      url: `https://www.googleapis.com/drive/v3/files/${fileId}?alt=media`,
      method: "GET",
      headers: { Authorization: `Bearer ${token}` }
    });
    if (resp.status >= 400)
      throw new Error(`Download failed (${resp.status}): ${resp.text}`);
    const folder = vaultPath.includes("/") ? vaultPath.substring(0, vaultPath.lastIndexOf("/")) : "";
    if (folder) {
      try {
        await this.app.vault.createFolder(folder);
      } catch (_) {
      }
    }
    const existing = this.app.vault.getAbstractFileByPath(vaultPath);
    if (existing instanceof import_obsidian.TFile) {
      await this.app.vault.modifyBinary(existing, resp.arrayBuffer);
    } else {
      await this.app.vault.createBinary(vaultPath, resp.arrayBuffer);
    }
  }
  // ── Upload file (base64 multipart — Android safe) ────
  async uploadFile(file, existingDriveId) {
    const token = await this.getAccessToken();
    const folderId = await this.getFolderId();
    const driveName = this.encodePath(file.path);
    const content = await this.app.vault.readBinary(file);
    const boundary = "gdrive_boundary_" + Math.random().toString(36).slice(2);
    const metadata = JSON.stringify(
      existingDriveId ? { name: driveName } : { name: driveName, parents: [folderId] }
    );
    const base64Content = this.arrayBufferToBase64(content);
    const bodyStr = `--${boundary}\r
Content-Type: application/json; charset=UTF-8\r
\r
${metadata}\r
--${boundary}\r
Content-Type: application/octet-stream\r
Content-Transfer-Encoding: base64\r
\r
${base64Content}\r
--${boundary}--`;
    const reqParams = {
      url: existingDriveId ? `https://www.googleapis.com/upload/drive/v3/files/${existingDriveId}?uploadType=multipart` : `https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart`,
      method: existingDriveId ? "PATCH" : "POST",
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": `multipart/related; boundary=${boundary}`
      },
      body: bodyStr
    };
    const resp = await (0, import_obsidian.requestUrl)(reqParams);
    if (resp.status >= 400)
      throw new Error(`Upload failed (${resp.status}): ${resp.text}`);
    this.lastSynced[file.path] = file.stat.mtime;
  }
  // ── Delete ──────────────────────────────────
  async deleteDriveFile(fileId) {
    const token = await this.getAccessToken();
    const resp = await (0, import_obsidian.requestUrl)({
      url: `https://www.googleapis.com/drive/v3/files/${fileId}`,
      method: "DELETE",
      headers: { Authorization: `Bearer ${token}` }
    });
    if (resp.status >= 400 && resp.status !== 404)
      throw new Error(`Delete failed (${resp.status}): ${resp.text}`);
  }
  // ── Sync ────────────────────────────────────
  async fullTwoWaySync() {
    var _a;
    try {
      if (this.isSyncing) {
        new import_obsidian.Notice("[GDrive Sync] Sync already in progress.");
        return;
      }
      if (!this.hasCredentials()) {
        new import_obsidian.Notice("[GDrive Sync] Please configure credentials in settings.");
        return;
      }
      this.isSyncing = true;
      this.setStatus("syncing");
      let downloaded = 0, uploaded = 0;
      try {
        const driveMap = await this.listDriveFiles();
        const toDownload = [];
        for (const [vaultPath, info] of Object.entries(driveMap)) {
          const localFile = this.app.vault.getAbstractFileByPath(vaultPath);
          const driveMs = new Date(info.modifiedTime).getTime();
          if (!localFile || localFile instanceof import_obsidian.TFile && driveMs > localFile.stat.mtime)
            toDownload.push({ id: info.id, vaultPath });
        }
        await this.runInBatches(toDownload, 3, async ({ id, vaultPath }) => {
          try {
            await this.downloadFile(id, vaultPath);
            downloaded++;
            this.setStatus("syncing", `\u2B07\uFE0F ${downloaded}...`);
          } catch (e) {
            console.error(`[GDrive Sync] Download error ${vaultPath}:`, this.errMsg(e));
          }
        });
        const toUpload = [];
        for (const file of this.app.vault.getFiles()) {
          const driveInfo = driveMap[file.path];
          const driveMs = driveInfo ? new Date(driveInfo.modifiedTime).getTime() : 0;
          const lastSyncedMs = (_a = this.lastSynced[file.path]) != null ? _a : 0;
          if (!driveInfo || file.stat.mtime > driveMs && file.stat.mtime > lastSyncedMs)
            toUpload.push({ file, existingId: driveInfo == null ? void 0 : driveInfo.id });
        }
        await this.runInBatches(toUpload, 3, async ({ file, existingId }) => {
          try {
            await this.uploadFile(file, existingId);
            uploaded++;
            this.setStatus("syncing", `\u2B06\uFE0F ${uploaded}...`);
          } catch (e) {
            console.error(`[GDrive Sync] Upload error ${file.path}:`, this.errMsg(e));
          }
        });
        await this.persistLastSynced();
        this.setStatus("done", `\u2705 \u2B07${downloaded} \u2B06${uploaded} \u2014 ${new Date().toLocaleTimeString()}`);
      } catch (e) {
        const msg = this.errMsg(e);
        console.error("[GDrive Sync] Sync error:", msg);
        new import_obsidian.Notice(`[GDrive Sync] Sync failed: ${msg}`, 8e3);
        this.setStatus("error");
      } finally {
        this.isSyncing = false;
      }
    } catch (e) {
      this.isSyncing = false;
      console.error("[GDrive Sync] Unexpected sync crash:", this.errMsg(e));
      new import_obsidian.Notice(`[GDrive Sync] Unexpected error: ${this.errMsg(e)}`, 8e3);
      this.setStatus("error");
    }
  }
  async downloadAllFromDrive() {
    try {
      if (this.isSyncing) {
        new import_obsidian.Notice("[GDrive Sync] Sync already in progress.");
        return;
      }
      if (!this.hasCredentials()) {
        new import_obsidian.Notice("[GDrive Sync] Please configure credentials in settings.");
        return;
      }
      this.isSyncing = true;
      this.setStatus("syncing");
      const driveMap = await this.listDriveFiles();
      const entries = Object.entries(driveMap);
      let count = 0;
      await this.runInBatches(entries, 3, async ([vaultPath, info]) => {
        try {
          await this.downloadFile(info.id, vaultPath);
          count++;
          this.setStatus("syncing", `\u2B07\uFE0F ${count}/${entries.length}...`);
        } catch (e) {
          console.error(`[GDrive Sync] Download error ${vaultPath}:`, this.errMsg(e));
        }
      });
      this.setStatus("done", `\u2705 \u2B07${count} \u2014 ${new Date().toLocaleTimeString()}`);
      new import_obsidian.Notice(`[GDrive Sync] Downloaded ${count} files.`);
    } catch (e) {
      new import_obsidian.Notice(`[GDrive Sync] Download failed: ${this.errMsg(e)}`, 8e3);
      this.setStatus("error");
    } finally {
      this.isSyncing = false;
    }
  }
  // ── Auto-sync ─────────────────────────────
  startAutoSync() {
    this.stopAutoSync();
    this.fullTwoWaySync();
    this.syncIntervalId = window.setInterval(() => {
      if (!this.isSyncing)
        this.fullTwoWaySync();
    }, this.settings.autoSyncInterval * 1e3);
    new import_obsidian.Notice(`[GDrive Sync] Auto-sync started (every ${this.settings.autoSyncInterval}s)`);
  }
  stopAutoSync() {
    if (this.syncIntervalId !== null) {
      window.clearInterval(this.syncIntervalId);
      this.syncIntervalId = null;
    }
    this.setStatus("idle");
  }
  // ── File event handlers ──────────────────────
  async onFileModified(file) {
    var _a, _b;
    try {
      if (file.stat.mtime - ((_a = this.lastSynced[file.path]) != null ? _a : 0) < 2e3)
        return;
      const driveMap = await this.listDriveFiles();
      await this.uploadFile(file, (_b = driveMap[file.path]) == null ? void 0 : _b.id);
    } catch (e) {
      console.error(`[GDrive Sync] Modify failed ${file.path}:`, this.errMsg(e));
    }
  }
  async onFileCreated(file) {
    try {
      await new Promise((r) => window.setTimeout(r, 1e3));
      await this.uploadFile(file, void 0);
    } catch (e) {
      console.error(`[GDrive Sync] Create failed ${file.path}:`, this.errMsg(e));
    }
  }
  async onFileDeleted(file) {
    try {
      const driveMap = await this.listDriveFiles();
      const info = driveMap[file.path];
      if (info)
        await this.deleteDriveFile(info.id);
      delete this.lastSynced[file.path];
    } catch (e) {
      console.error(`[GDrive Sync] Delete failed ${file.path}:`, this.errMsg(e));
    }
  }
  async onFileRenamed(file, oldPath) {
    try {
      const driveMap = await this.listDriveFiles();
      const oldInfo = driveMap[oldPath];
      if (oldInfo)
        await this.deleteDriveFile(oldInfo.id);
      delete this.lastSynced[oldPath];
      await this.uploadFile(file, void 0);
    } catch (e) {
      console.error(`[GDrive Sync] Rename failed ${file.path}:`, this.errMsg(e));
    }
  }
  // ── Auto-updater ───────────────────────────
  async silentUpdateCheck() {
    var _a, _b;
    try {
      const base = "https://raw.githubusercontent.com/JanakaProjects/gdrive-vault-sync/main";
      const mResp = await (0, import_obsidian.requestUrl)({ url: `${base}/manifest.json`, method: "GET" });
      if (mResp.status >= 400)
        return;
      const remoteVer = (_a = mResp.json) == null ? void 0 : _a.version;
      const localVer = (_b = this.manifest) == null ? void 0 : _b.version;
      if (!remoteVer || !localVer || remoteVer === localVer)
        return;
      new import_obsidian.Notice(`[GDrive Sync] Update v${localVer} \u2192 v${remoteVer}. Updating...`);
      const jsResp = await (0, import_obsidian.requestUrl)({ url: `${base}/main.js`, method: "GET" });
      if (jsResp.status >= 400) {
        new import_obsidian.Notice(`[GDrive Sync] Update failed: could not fetch main.js`, 8e3);
        return;
      }
      const dir = `.obsidian/plugins/gdrive-vault-sync`;
      await this.app.vault.adapter.write(`${dir}/main.js`, jsResp.text);
      await this.app.vault.adapter.write(`${dir}/manifest.json`, JSON.stringify(mResp.json, null, 2));
      new import_obsidian.Notice(`[GDrive Sync] Updated to v${remoteVer}! Reloading...`);
      await this.app.plugins.disablePlugin("gdrive-vault-sync");
      await this.app.plugins.enablePlugin("gdrive-vault-sync");
    } catch (e) {
      console.warn("[GDrive Sync] Silent update check failed:", this.errMsg(e));
    }
  }
  async checkForUpdate() {
    var _a, _b;
    try {
      const base = "https://raw.githubusercontent.com/JanakaProjects/gdrive-vault-sync/main";
      const mResp = await (0, import_obsidian.requestUrl)({ url: `${base}/manifest.json`, method: "GET" });
      if (mResp.status >= 400)
        throw new Error(`Failed to fetch manifest: ${mResp.status}`);
      const remoteVer = (_a = mResp.json) == null ? void 0 : _a.version;
      const localVer = (_b = this.manifest) == null ? void 0 : _b.version;
      if (remoteVer === localVer) {
        new import_obsidian.Notice(`[GDrive Sync] Already up to date (v${localVer})`);
        return;
      }
      new import_obsidian.Notice(`[GDrive Sync] Updating v${localVer} \u2192 v${remoteVer}...`);
      const jsResp = await (0, import_obsidian.requestUrl)({ url: `${base}/main.js`, method: "GET" });
      if (jsResp.status >= 400)
        throw new Error(`Failed to fetch main.js: ${jsResp.status}`);
      const dir = `.obsidian/plugins/gdrive-vault-sync`;
      await this.app.vault.adapter.write(`${dir}/main.js`, jsResp.text);
      await this.app.vault.adapter.write(`${dir}/manifest.json`, JSON.stringify(mResp.json, null, 2));
      new import_obsidian.Notice(`[GDrive Sync] Update complete! Reloading...`);
      await this.app.plugins.disablePlugin("gdrive-vault-sync");
      await this.app.plugins.enablePlugin("gdrive-vault-sync");
    } catch (e) {
      new import_obsidian.Notice(`[GDrive Sync] Update check failed: ${this.errMsg(e)}`, 8e3);
    }
  }
};
var GDriveSyncSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "GDrive Vault Sync \u2014 Settings" });
    new import_obsidian.Setting(containerEl).setName("Client ID").setDesc("Google OAuth 2.0 Client ID").addText((t) => t.setPlaceholder("Enter your Client ID").setValue(this.plugin.settings.clientId).onChange(async (v) => {
      this.plugin.settings.clientId = v.trim();
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Client Secret").setDesc("Google OAuth 2.0 Client Secret").addText((t) => t.setPlaceholder("Enter your Client Secret").setValue(this.plugin.settings.clientSecret).onChange(async (v) => {
      this.plugin.settings.clientSecret = v.trim();
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Refresh Token").setDesc("Long-lived OAuth 2.0 Refresh Token").addText((t) => t.setPlaceholder("Enter your Refresh Token").setValue(this.plugin.settings.refreshToken).onChange(async (v) => {
      this.plugin.settings.refreshToken = v.trim();
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Drive Folder Name").setDesc("Folder in Google Drive").addText((t) => t.setPlaceholder("ObsidianVaultSync").setValue(this.plugin.settings.driveFolderName).onChange(async (v) => {
      this.plugin.settings.driveFolderName = v.trim() || "ObsidianVaultSync";
      this.plugin["driveFolderId"] = "";
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Auto-sync interval (seconds)").setDesc("1\u2013300 seconds").addSlider((s) => s.setLimits(1, 300, 1).setValue(this.plugin.settings.autoSyncInterval).setDynamicTooltip().onChange(async (v) => {
      this.plugin.settings.autoSyncInterval = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Auto-sync on open").setDesc("Start syncing when Obsidian opens").addToggle((t) => t.setValue(this.plugin.settings.autoSyncOnStart).onChange(async (v) => {
      this.plugin.settings.autoSyncOnStart = v;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Actions" });
    new import_obsidian.Setting(containerEl).setName("\u25B6 Start Auto-Sync").setDesc("Begin automatic sync at configured interval").addButton((b) => b.setButtonText("Start").setCta().onClick(() => this.plugin.startAutoSync()));
    new import_obsidian.Setting(containerEl).setName("\u23F8 Stop Auto-Sync").setDesc("Stop the automatic sync interval").addButton((b) => b.setButtonText("Stop").onClick(() => {
      this.plugin.stopAutoSync();
      new import_obsidian.Notice("[GDrive Sync] Auto-sync stopped.");
    }));
    new import_obsidian.Setting(containerEl).setName("\u{1F504} Two-Way Sync Now").setDesc("Immediately run a full two-way sync").addButton((b) => b.setButtonText("Sync Now").setCta().onClick(() => this.plugin.fullTwoWaySync()));
    new import_obsidian.Setting(containerEl).setName("\u2B07 Download All from Drive").setDesc("Force-download every file from Google Drive").addButton((b) => b.setButtonText("Download All").onClick(() => this.plugin.downloadAllFromDrive()));
    new import_obsidian.Setting(containerEl).setName("\u{1F504} Check for Update").setDesc("Fetch latest version from GitHub and auto-update").addButton((b) => b.setButtonText("Check Update").onClick(() => this.plugin.checkForUpdate()));
  }
};
